/**
 * Gap report for the liquor store type: carried leaves with no Mercaso SKU in
 * data/matches/liquor.csv (rejected rows don't count). A gap means Mercaso has no active item
 * that fits, so it is a sourcing question, not a matching one. Writes
 * docs/exploration/liquor-gaps.md. Needs no Athena data, so it runs anywhere.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadCatalog } from "../lib/load.ts";
import { summarizeMatches } from "../lib/matches.ts";
import { buildCatalogJson, type OutputNode } from "../lib/output.ts";

const ROOT = process.cwd();
const { storeTypes } = loadCatalog(ROOT);
const liquor = storeTypes.find((s) => s.resolved.def.store_type === "liquor");
if (!liquor) throw new Error("store type liquor not found");
const tree = buildCatalogJson(liquor.resolved, summarizeMatches(liquor.matches, liquor.resolved));

interface Gap {
  id: string;
  path: string;
  priority: string;
}
const gaps: Gap[] = [];
let leaves = 0;
let withSku = 0;
const walk = (n: OutputNode, path: string[]) => {
  const here = [...path, n.name];
  if (!n.children || n.children.length === 0) {
    if (!n.priority) return; // links to canonical nodes carry no priority of their own
    leaves++;
    if ((n.match?.skus.length ?? 0) > 0) withSku++;
    else gaps.push({ id: n.id, path: here.join(" › "), priority: n.priority });
    return;
  }
  for (const c of n.children) walk(c, here);
};
for (const d of tree.departments) walk(d, []);

const section = (priority: string) => {
  const list = gaps.filter((g) => g.priority === priority);
  if (list.length === 0) return `## ${priority}\n\nNone.\n`;
  return `## ${priority} (${list.length})\n\n| Item | Id |\n|---|---|\n${list.map((g) => `| ${g.path} | \`${g.id}\` |`).join("\n")}\n`;
};

const md = `# Liquor store gaps — Mercaso items not found

Generated by \`pnpm gaps\` from \`data/matches/liquor.csv\`. Do not edit by hand.

A gap is a carried item with no active Mercaso SKU matched to it, after review. Mercaso either
doesn't stock it or stocks it under a name the matcher and the review didn't connect. Either way it
is a question for sourcing: stock it, find it, or drop it from the catalog.

**${withSku} of ${leaves} items have at least one Mercaso SKU; ${gaps.length} have none.**

${section("must")}
${section("should")}
${section("nice")}`;
writeFileSync(join(ROOT, "docs/exploration/liquor-gaps.md"), md);
console.log(`wrote docs/exploration/liquor-gaps.md: ${gaps.length} gaps of ${leaves} items`);
